<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Chat;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{
    const LIMIT = 100;

    /**
     * @param int $limit
     *
     * @return array
     */
    public function getAllApproved($limit = self::LIMIT)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
                FROM AppBundle:Chat c
                WHERE c.status = :status
                ORDER BY c.approvedAt'
            )->setParameter('status', Chat::STATUS_APPROVED)
            ->getResult();
    }

    /**
     * @return array
     */
    public function getAllUnApproved()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
                FROM AppBundle:Chat c
                WHERE c.status = :status
                ORDER BY c.createdAt ASC'
            )->setParameter('status', Chat::STATUS_PENDING)
            ->getResult();
    }

}
